### ISSUE TITLE
Warn about requiring git-lfs for cloning

### ISSUE THREAD

**Issue by skullbunnygalaxy** [danisztls/lite-search#1]
Every time I try to git clone lite-search, I get the following issue:

``` bash
git clone https://github.com/danisztls/lite-search.git
Cloning into 'lite-search'...
remote: Enumerating objects: 684, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 684 (delta 3), reused 6 (delta 3), pack-reused 675
Receiving objects: 100% (684/684), 181.06 KiB | 2.87 MiB/s, done.
Resolving deltas: 100% (338/338), done.
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

When I do `git status` it shows that it deletes the vast majority of repo after clone it. When I attempt to follow the recommendations it continues to fail. 

I eventually figured out that I needed to install git-lfs in order to get the repo to install correctly. I recommend adding to the readme that this is a pre-requisite.

**Comment by danisztls** [comment]
Thanks @skullbunnygalaxy. Updated by https://github.com/danisztls/lite-search/commit/e9733cb89e952d4bbc94357ab134099edf1f4007

Git LFS is used to store the standalone artifacts at `build/` but it isn't a pre-requisite. But I see now that cloning is the easier way to obtain those as I'm not using GitHub Releases or providing a CDN.
